### ISSUE TITLE
error: AC_INIT should be called with package and version arguments

### ISSUE THREAD

**Issue by fatalfeel** [autotools-mirror/gettext#1]
error: AC_INIT should be called with package and version arguments

fix this way

~/gettext-0.20.1/libtextstyle/configure.ac
AC_PREREQ([2.63])
AC_INIT([libtextstyle],[0.20.1])                                              #add package and version
AC_CONFIG_SRCDIR([version.sh])
AC_CONFIG_AUX_DIR([build-aux])
. $srcdir/version.sh
#gl_INIT_PACKAGE([libtextstyle], [$VERSION_NUMBER]) #comment this
AM_INIT_AUTOMAKE([1.13 silent-rules])
AM_CONFIG_HEADER([config.h])

**Comment by TimothyGu** [comment]
This is a read-only mirror of GNU gettext. See https://www.gnu.org/software/gettext/ and the `HACKING` file on how to contribute.
